# copied from overlord's .pre-commit-config.yaml except line length is changed to 150
repos:
###############################################################################
# isort alphabetizes your python imports and groups them
#
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      args:
        - --check-only
        - -l=150
        - --py=310
        - --profile=black
        - --skip-glob=spa"
        - --skip-gitignore
        - --filter-files
###############################################################################
# #
#  blue auto-formats python files for us
- repo: https://github.com/grantjenks/blue.git
  rev: v0.8.0
  hooks:
  - id: blue
    args:
      - -l150
      - -tpy39
###############################################################################
# after blue is done reformatting everything, double check it with flake8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args:
      - --max-line-length=150
      - --ignore=E265,E266,W503,W504,F811
###############################################################################
# bandit runs security checks on our python
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args:
        - -v
        - --skip=B104
        - -x="./.git"
        - -ii
        - -ll
      files: \.(py|py3|pyc|pyo|pyw|pyx|pyd|pxd|pyi|pyz|pywz|rpy|pyde|pyp|pyt|xpy|ipynb)$
###############################################################################
# safety makes sure our python dependencies don't have vulnerabilities
# 
# The precommit hook runs against any file that you change which has "requirements" in the name.
#
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.4
  hooks:
    -   id: python-safety-dependencies-check
        files: requirements
        args: 
            - --short-report
###############################################################################
# lint the shell scripts too
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
        args: 
            - --severity=warning
